enableAllRules = true

[rule.var-naming]
arguments = [[], [], [{ skipInitialismNameChecks = true }]]

[rule.line-length-limit]
arguments = [100]

[rule.empty-lines]
disabled = true

[rule.comment-spacings]
arguments = ["/***"]

[rule.add-constant]
arguments = [{allowStrs = "\"\"", allowInts = "0,1"}]